# Generated by Django 5.1 on 2024-08-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='import_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pensioner_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('add1', models.CharField(blank=True, max_length=200, null=True)),
                ('add2', models.CharField(blank=True, max_length=200, null=True)),
                ('birth', models.DateField(blank=True, max_length=20, null=True)),
                ('ptype', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('grouping', models.CharField(blank=True, max_length=100, null=True)),
                ('conmonth', models.CharField(blank=True, max_length=100, null=True)),
                ('readyx', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pensioner_list',
            },
        ),
        migrations.CreateModel(
            name='ticket_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_issued', models.DateField(blank=True, max_length=20, null=True)),
                ('valid_until', models.DateField(blank=True, max_length=20, null=True)),
                ('endorsed_to', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_ssp_consult', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('ticket_ssp_lab', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('ticket_family_consult', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('ticket_family_lab', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('checkup_status', models.CharField(default='Pending_Checkup', max_length=200)),
                ('checkup_type', models.CharField(blank=True, max_length=100, null=True)),
                ('recepient_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
