# Generated by Django 5.1 on 2024-08-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pensioner_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('add1', models.CharField(blank=True, max_length=200, null=True)),
                ('add2', models.CharField(blank=True, max_length=200, null=True)),
                ('birth', models.DateField(blank=True, max_length=20, null=True)),
                ('ptype', models.DateField(blank=True, max_length=20, null=True)),
                ('status', models.DateField(blank=True, max_length=20, null=True)),
                ('grouping', models.DateField(blank=True, max_length=20, null=True)),
                ('conmonth', models.DateField(blank=True, max_length=20, null=True)),
                ('readyx', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pensioner_list',
            },
        ),
    ]
