# Generated by Django 5.1 on 2024-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_list',
            name='counter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
