# Generated by Django 5.1 on 2024-08-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensioner_list',
            name='conmonth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pensioner_list',
            name='grouping',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pensioner_list',
            name='ptype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pensioner_list',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
