# Generated by Django 5.1 on 2024-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ticket_list_counter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_list',
            name='checkup_status',
            field=models.CharField(default='PENDING_CHECKUP', max_length=200),
        ),
    ]
