# Generated by Django 5.1 on 2024-08-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ticket_list_ticket_num_family_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_list',
            old_name='ticket_num_family',
            new_name='ticket_family_consult',
        ),
        migrations.RenameField(
            model_name='ticket_list',
            old_name='ticket_num_ssp',
            new_name='ticket_family_lab',
        ),
        migrations.AddField(
            model_name='ticket_list',
            name='checkup_status',
            field=models.CharField(default='Pending_Checkup', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket_list',
            name='ticket_ssp_consult',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket_list',
            name='ticket_ssp_lab',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
