# Generated by Django 5.1 on 2024-08-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_ticket_num_family_ticket_list_ticket_family_consult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_list',
            name='checkup_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
