# Generated by Django 5.1 on 2024-08-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pensioner_list_conmonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='import_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
