# Generated by Django 5.1 on 2024-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ticket_list_checkup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_list',
            name='checkup_status',
            field=models.CharField(default='PENDING CHECKUP', max_length=200),
        ),
    ]
