# Generated by Django 5.1 on 2024-08-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ticket_list_checkup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_list',
            name='recepient_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
