# Generated by Django 5.1 on 2024-09-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ticket_list_checkup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner_list',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
