# Generated by Django 5.1 on 2024-08-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pensioner_list_csv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_issued', models.DateField(blank=True, max_length=20, null=True)),
                ('valid_until', models.DateField(blank=True, max_length=20, null=True)),
                ('endorsed_to', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
