# Generated by Django 5.1 on 2024-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pensioner_list_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_history',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
